name: AWS_Serverless_Deploy

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      SERVERLESS_ACCESS_KEY:
        required: true
    inputs:
      deploy_environment:
        description: 'Choose an environment'
        required: true
        default: "staging"
        type: string
      region:
        description: 'Choose the region you want to deploy'
        required: false
        default: 'us-east-1'
        type: string
      force:
        description: 'Execute force deployment, even if no changes exist'
        required: false
        default: 'false'
        type: string
      debug:
        description: 'Enable debug?'
        required: false
        default: false
        type: boolean
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:22.14'
        type: string
      stage:
        description: 'Select the desired stage for deployment'
        required: true
        default: 'staging'
        type: string

env:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1,
  AWS_SDK_LOAD_CONFIG: 1
  AWS_REGION: ${{ inputs.region }}
  debugMode: ${{ inputs.debug }}

jobs:
  analysis:
    uses: stetind/ppc-reusable-workflows/.github/workflows/typescript.yaml@v7.0.0
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}
  deploy:
    needs: analysis
    uses: stetind/ppc-reusable-workflows/.github/workflows/aws-serverless-deploy.yaml@v7.0.0
    secrets: inherit
    with:
      deploy_environment: ${{ inputs.deploy_environment }}
      region: ${{ inputs.region }}
      force: ${{ inputs.force }}
      debug: ${{ inputs.debug }}
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}
      stage: ${{ inputs.stage }}
