name: Cloudflare_Deploy

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      CF_API_TOKEN:
        required: true
    inputs:
      deploy_environment:
        description: 'Choose an environment'
        required: true
        type: string
      debug:
        description: 'Enable debug?'
        required: false
        default: false
        type: boolean
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:22.14'
        type: string

jobs:
  analysis:
    uses: stetind/ppc-reusable-workflows/.github/workflows/typescript.yaml@v7.0.0
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}

  deploy:
    needs: analysis
    uses: stetind/ppc-reusable-workflows/.github/workflows/cloudflare-wrangler-deploy.yaml@v7.0.0
    secrets: inherit
    with:
      deploy_environment: ${{ inputs.deploy_environment }}
      debug: ${{ inputs.debug }}
      runner: ${{ inputs.runner }}
      job_container: ${{ inputs.job_container }}
