name: Cypress Test
on:
  workflow_call:
    secrets:
      CYPRESS_USER_PASSWORD:
        required: true
      NPM_TOKEN:
        required: true
    inputs:
      host:
        description: 'Define teh host to test'
        required: true
        type: string
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
jobs:
  cypress-run:
    runs-on: ${{ inputs.runner }}
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user root
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup Node and NPM
        uses: stetind/ppc-npm-global-dependencies-action@v4.0
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}

      - name: 🔧 Npm Configure
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --config-file cypress.config.github.ts
        env:
          cypressUserEmail: ${{ vars.CYPRESS_USER_EMAIL }}
          cypressUserPassword: ${{ secrets.CYPRESS_USER_PASSWORD }}
          awsHost: ${{ inputs.host }}
          awsRegion: 'us-east-1'

