# =============================================================================
# 🧪 Cypress E2E Tests
# Runs Cypress tests using a defined browser and base URL.
# Inputs:
#   - base_url: Base URL to test against
#   - browser: Which browser to use (e.g. chrome, electron)
#   - record: Enable Cypress dashboard recording
# =============================================================================

name: Cypress Test
on:
  workflow_call:
    secrets:
      CYPRESS_USER_PASSWORD:
        required: true
      NPM_TOKEN:
        required: true
    inputs:
      deploy_environment:
        description: 'Choose an environment'
        required: true
        default: "staging"
        type: string
      host:
        description: 'Define teh host to test'
        required: true
        type: string
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      configuration:
        description: 'Set the configuration file name'
        required: false
        default: 'cypress.config.github.ts'
        type: string
jobs:
  cypress-run:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.deploy_environment }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user root
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup Node and NPM
        uses: stetind/ppc-github-composite-actions/.github/actions/intall-global-dependencies@1.0.0
        with:
          npm_token: $NPM_TOKEN

      - name: 🔧 Npm Configure
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NODE_AUTH_TOKEN: $NPM_TOKEN
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --config-file ${{ inputs.configuration }}
        env:
          cypressUserEmail: ${{ vars.CYPRESS_USER_EMAIL }}
          cypressUserPassword: ${{ secrets.CYPRESS_USER_PASSWORD }}
          cypressTestClientUsername: ${{ vars.CYPRESS_TEST_CLIENT_USERNAME }}
          cypressTestClientPassword: ${{ secrets.CYPRESS_TEST_CLIENT_PASSWORD }}
          cypressTestClientId: ${{ vars.CYPRESS_TEST_CLIENT_ID }}
          awsHost: ${{ inputs.host }}
          awsRegion: 'us-east-1'

