name: Cypress Test

on:
  workflow_call:
    inputs:
      host:
        description: Api host
        type: string
        required: true
      group:
        description: concurrency group name
        type: string
        default: ${{ github.workflow }}
        required: false
      npm_token:
        description: NPM TOKEN
        type: string
        default: ${{ secrets.NPM_TOKEN }}
        required: false
      config_file:
        type: string
        default: 'cypress.config.github.ts'
        required: false

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.group }}
      cancel-in-progress: true
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup Node and NPM
        uses: stetind/ppc-npm-global-dependencies-action@v3
        with:
          npm_token: ${{ inpputs.npm_token }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --config-file ${{ inpputs.config_file }}
        env:
          apiHost: ${{ inputs.host }}
