# =============================================================================
# 🧹 ESLint Linter Check
# Runs ESLint across your TypeScript/JavaScript project and fails on lint errors.
# Inputs:
#   - folder: Folder to lint (default is root)
#   - eslint_config: Optional path to a custom ESLint config file
# =============================================================================

name: Typescript eslint

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: 'Choose the runner'
        required: false
        default: 'self-hosted'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:22.14'
        type: string

jobs:
  eslint:
    name: Run EsLint
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.job_container }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4
      
      - name: 🔧 Setup Node and NPM
        uses: stetind/ppc-github-composite-actions/.github/actions/intall-global-dependencies@1.0.0
        with:
          npm_token: $NPM_TOKEN

      - name: 🚀 Run Eslint
        run: npm run lint-quiet