name: 🧹 Delete All Workflow Runs
run-name: 🧹 Delete all `${{ inputs.status }}` of (${{ inputs.workflow_name || 'all' }} )

on:
  workflow_call:
    inputs:
      status:
        description: |
          Optional status filter for workflow runs. Available options:
          • completed - All completed runs
          • action_required - Runs that require action
          • cancelled - Manually cancelled runs
          • failure - Failed runs
          • neutral - Runs with neutral outcome
          • skipped - Skipped runs
          • stale - Stale runs
          • success - Successful runs
          • timed_out - Runs that exceeded time limit
          • queued - Queued runs
          • requested - Requested runs
          • waiting - Waiting runs
          • pending - Pending runs
        type: string
        required: false
        default: 'cancelled'
      workflow_name:
        description: 'The name of the workflow to delete runs for (e.g., "CI Workflow")'
        required: false
        type: string
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string

  workflow_dispatch:
    inputs:
      status:
        description: |
          Optional status filter for workflow runs. Available options:
          • completed - All completed runs
          • action_required - Runs that require action
          • cancelled - Manually cancelled runs
          • failure - Failed runs
          • neutral - Runs with neutral outcome
          • skipped - Skipped runs
          • stale - Stale runs
          • success - Successful runs
          • timed_out - Runs that exceeded time limit
          • queued - Queued runs
          • requested - Requested runs
          • waiting - Waiting runs
          • pending - Pending runs
        type: choice
        required: false
        default: 'cancelled'
        options:
          - completed
          - action_required
          - cancelled
          - failure
          - neutral
          - skipped
          - stale
          - success
          - timed_out
          - queued
          - requested
          - waiting
          - pending
      workflow_name:
        description: 'The name of the workflow to delete runs for (e.g., "CI Workflow")'
        required: false
        type: string
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'self-hosted'
          - 'ubuntu-latest'

jobs:
  cleanup:
    runs-on: ${{ inputs.runner }}
    container: 'node:22.14'
    steps:
      - name: 🔐 Get GitHub App Token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.PPC_CI_APP_ID }}
          private-key: ${{ secrets.PPC_CI_APP_PRIVATE_KEY }}

      - name: Cleanup
        uses: stetind/ppc-github-composite-actions/.github/actions/maintenance-cleanup@v2.0.2
        with:
          token: ${{ steps.get_token.outputs.token }}
          status: ${{ inputs.status }}
          workflow_name: ${{ inputs.workflow_name }}