# =============================================================================
# 🧹 Release Branch Cleanup
#
# Description:
#   A reusable workflow for handling post-release branch management, including
#   merging changes and cleaning up temporary branches.
#
# Key Features:
#   • Creates and processes pull requests
#   • Merges changes to target branch
#   • Cleans up temporary branches
#   • Provides execution summary
#
# Required Inputs:
#   • title: PR title for the merge
#   • merge_option: Strategy for branch handling
#   • source: Source branch to merge from
#   • target: Target branch to merge into
#   • runner: (optional) CI runner selection
#
# Required Permissions:
#   • GITHUB_TOKEN with repository write access
#
# Usage:
#   Called by release-execution.yaml during release process
# =============================================================================

name: 🧹 Merge and clean branches

on:
  workflow_call:
    secrets:
      WORKFLOW_TOKEN:
        description: 'GitHub token with permissions for PR creation, branch merging, and deletion'
        required: true
    inputs:
      title:
        description: 'Title of the pull request to be created (typically includes version number)'
        required: true
        type: string
      body:
        description: 'Body of the pull request to be created (typically includes version number)'
        required: false
        type: string
        default: ''
      merge_option:
        description: 'Strategy for branch handling (merge and delete, merge, or none)'
        required: true
        type: string
      source:
        description: 'Source branch containing the changes to be merged'
        required: true
        type: string
      target:
        description: 'Target branch where changes will be merged (typically main)'
        required: true
        type: string
      runner:
        description: 'GitHub-hosted runner or self-hosted runner label for job execution'
        required: false
        default: 'ubuntu-latest'
        type: string

jobs:
  release:
    name: Merge and clean branches
    runs-on: ${{ inputs.runner }}
    container: 'ubuntu:latest'
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⬇️ Create Pull Request
        id: pr
        uses: stetind/ppc-github-composite-actions/.github/actions/pull-request-create@v1.0.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: ${{ inputs.title }}
          source: ${{ inputs.source }}
          target: ${{ inputs.target }}
          body: ${{ inputs.body }}

      - name: 🧹 Merge
        id: merge
        if: ${{ inputs.merge_option != 'none' }}
        uses: stetind/ppc-github-composite-actions/.github/actions/pull-request-merge@v1.0.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          pr_url: ${{ steps.pr.outputs.pr_url }}

      - name: 🗑️ Delete `releases` Branch
        if: ${{ inputs.merge_option == 'merge and delete' && steps.merge.outcome == 'success' }}
        uses: stetind/ppc-github-composite-actions/.github/actions/delete-bracnh@v1.0.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: ${{ inputs.source }}
