# =============================================================================
# ✅ Serverless Validate
#
# This workflow validates a Serverless Framework configuration:
# - Ensures the serverless.yml file is valid
# - Verifies configuration for specified stage and region
# - Validates AWS credentials and permissions
#
# Inputs:
#   - deploy_environment: Environment to validate (default: staging)
#   - region: AWS region (default: us-east-1) 
#   - runner: GitHub runner to use (default: self-hosted)
#   - job_container: Docker container image (default: node:20.13)
#
# Required Secrets:
#   - NPM_TOKEN
#   - SERVERLESS_ACCESS_KEY
#   - AWS_SECRET_ACCESS_KEY
#   - AWS_ACCESS_KEY_ID
#
# Trigger: workflow_call
# =============================================================================

name: AWS_Serverless_Validate

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      SERVERLESS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
    inputs:
      deploy_environment:
        description: 'Choose an environment:'
        required: true
        default: "staging"
        type: string
      region:
        description: 'Choose a region:'
        required: false
        default: 'us-east-1'
        type: string
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:20.13'
        type: string

env:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1,
  AWS_SDK_LOAD_CONFIG: 1
  AWS_REGION: ${{ inputs.region }}
  REGION: ${{ inputs.region }}
  debugMode: 'false'

jobs:
  validate_serverless:
    name: Validate Serverless
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.deploy_environment }}
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      PPC_STAGE: ${{ vars.PPC_STAGE || vars.PPCENV_PPC_STAGE }}
      REGION: ${{ inputs.region || vars.PPCENV_REGION }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    container:
      image: ${{ inputs.job_container }}
      volumes:
        - ${{ github.workspace }}:/workspace
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🧙 Install Node
        uses: stetind/ppc-github-composite-actions/.github/actions/install-global-dependencies@v1.0.5
        with:
          npm_token: $NPM_TOKEN

      - name: 📓 Create [dot] env
        uses: stetind/ppc-github-composite-actions/.github/actions/create-dot-env@v1.0.5
        with:
          volume: '/workspace'
          secrets: ${{ toJSON(secrets) }}
          variables: ${{ toJSON(vars) }}

      - name: 🚅 Serverless Validate
        run: npm run sls-print