name: SonarCloud Coverage

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: 'Choose the runner'
        required: false
        default: 'self-hosted'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:20.13'
        type: string

jobs:
  testing:
    name: Run Jest Tests
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.job_container }}

    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup Node and NPM
        uses: stetind/ppc-npm-global-dependencies-action@v4.0
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}

      - name: 🔧 Building Environment
        run: npm run build --if-present && npx browserslist@latest --update-db

      - name: 🔧 Run Tests
        id: run_test
        run: npm run test:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}