name: Typescript CI

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:20.13'
        type: string

env:
  VERSION: 'main'

jobs:
  eslint:
    uses: stetind/ppc-reusable-workflows/.github/workflows/eslint.yaml@$VERSION
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}

  testing:
    needs: eslint
    uses: stetind/ppc-reusable-workflows/.github/workflows/tests.yaml@$VERSION
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}
