name: Typescript CI

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      node_version:
        description: 'The desired node version'
        required: false
        default: '20'
        type: string
      runner:
        description: 'Choose the runner'
        required: false
        default: 'self-hosted'
        type: string

jobs:
  eslint:
    uses: stetind/ppc-reusable-workflows/.github/workflows/eslint.yaml@v3
    secrets: inherit
    with:
      node_version: ${{ inputs.node_version }}
      runner: ${{ inputs.runner }}

  testing:
    needs: eslint
    uses: stetind/ppc-reusable-workflows/.github/workflows/tests.yaml@v3
    secrets: inherit
    with:
      node_version: ${{ inputs.node_version }}
      runner: ${{ inputs.runner }}