# =============================================================================
# 🧰 TypeScript Project Setup
# Installs dependencies, builds TypeScript, and optionally runs lint and tests.
# Inputs:
#   - run_lint: Run ESLint if true
#   - run_tests: Run test script if true
# =============================================================================

name: Typescript CI

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:22.14'
        type: string

jobs:
  eslint:
    name: Run EsLint
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.job_container }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v5

      - name: 🔧 Setup Node and NPM
        uses: stetind/ppc-github-composite-actions/.github/actions/install-global-dependencies@v1.0.6
        with:
          npm_token: $NPM_TOKEN

      - name: 🚀 Run Eslint
        run: npm run lint-quiet

  testing:
    name: Run Jest Tests
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.job_container }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v5

      - name: 🔧 Setup Node and NPM
        uses: stetind/ppc-github-composite-actions/.github/actions/install-global-dependencies@v1.0.6
        with:
          npm_token: $NPM_TOKEN

      - name: 🔧 Building Environment
        run: npm run build --if-present && npx browserslist@latest --update-db

      - name: 🔧 Run Tests
        id: run_test
        run: npm run test:ci
