name: Typescript CI

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:20.13'
        type: string

jobs:
  eslint:
    uses: stetind/ppc-reusable-workflows/.github/workflows/eslint.yaml@v5.2
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}

  testing:
    needs: eslint
    uses: stetind/ppc-reusable-workflows/.github/workflows/tests.yaml@v5.2
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}

    steps:
      - name: 🧙 Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
        env:
          TZ: UTC

      - name: 🔧 Setup Npm
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🔧 Install Dependencies
        run: npm ci

      - name: 🔧 Run Custom Command
        run: echo "This is a custom step added to the reusable workflow"

