# =============================================================================
# 🧰 TypeScript Project Setup
# Installs dependencies, builds TypeScript, and optionally runs lint and tests.
# Inputs:
#   - run_lint: Run ESLint if true
#   - run_tests: Run test script if true
# =============================================================================

name: Typescript CI

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      runner:
        description: 'Choose the runner'
        required: false
        default: 'ubuntu-latest'
        type: string
      job_container:
        description: 'Select the docker container for the action'
        required: false
        default: 'node:22.14'
        type: string

jobs:
  eslint:
    uses: stetind/ppc-reusable-workflows/.github/workflows/eslint.yaml@v8.2.0
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}

  testing:
    needs: eslint
    uses: stetind/ppc-reusable-workflows/.github/workflows/tests.yaml@v8.2.0
    secrets: inherit
    with:
      job_container: ${{ inputs.job_container }}
      runner: ${{ inputs.runner }}
